### ISSUE TITLE
Login process has cleartext passwords!

### ISSUE THREAD

**Issue by peterdrier** [ezesoft/xapi#1]
It's 2021 and this is a newly rolled out API having the API developers handling cleartext user passwords.  I can see the WSJ headline already...  How this got past any compliance/legal folks literally baffles me.  

Oauth2 exists for a reason. No API should be handling user's passwords directly these days.  Lest some nefarious developer out there siphons off passwords and causes significant trouble on the global financial markets some day.

**Comment by rbaxter1** [comment]
xAPI uses the SRP protocol (http://srp.stanford.edu/ndss.html) to authenticate. Additionally, all client-server communication is TLS encrypted. The tutorials are designed to showcase APIs and to keep it simple, bypassing SRP (which is an involved connection process) so the reader can focus on the functionality being explained. There is an example of production SRP connect procedure here: https://github.com/ezesoft/xapi/blob/master/examples/srp_connect.py

**Comment by peterdrier** [comment]
As the user of the API, I'm handling clear text passwords as can clearly be seen in your connect request message:

message ConnectRequest
{
	string UserName = 1;
	string Domain = 2;
	string **Password** = 3;
	string Locale = 4;
} 

That's a 101 level security problem.  Even your SRP example has the developer handling a cleartext password on line 23.  Sure it may not be going over the wire insecurely, but there's nothing preventing a nefarious developer from syphoning off passwords.  

As a fintech app developer, I literally CAN'T use this API because I'm not willing to take the liability of touching a user's passwords for an external system like this.  No other developers in their right mind should do so either.

**Comment by rbaxter1** [comment]
Peter, Thank you for the feedback. Depending on your tech stack, there are multiple common and standard techniques for secrets management. Eze currently doesn't manage issues through github, so kindly reach out to your customer service rep. She can connect us and I'm happy to discuss further. Thank you, Rob
